version: "3"

services:
  backend:
    image: sylvanld/shopping-backend
    networks:
      - www
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.shopping-backend.rule: "Host(`api.shopping.sylvan.ovh`)"
        traefik.http.services.shopping-backend.loadbalancer.server.port: "80"
        traefik.docker.network: "www"
        
networks:
  www:
    external: true
